### PR TITLE
added User Profile page

### PR DESCRIPTION
**Pull request by Happy22LC**

### CODE REVIEW

**Comment by astakes90** [comment]
Pulled this onto my machine and it works.

**Review by astakes90 — APPROVED** [review]
Pulled this onto my computer and it is working!

**Review by priya12845 — APPROVED** [review]
Works fine on my computer as well!

**Comment by TashaNaps42** [comment]
Looks good!

**Review by TashaNaps42 — APPROVED** [review]
Looks good!

This is my first review. I didn't know what I was doing lol

**Pull request merged**
