### PR TITLE
Tried pulling in API data

### PR DESCRIPTION
**Pull request by priya12845**
Tried pulling in API data on the same mywatchlist link. I just made change in the same mywatchlist.js file. Please check. This is my try. I am not able to display the data properly though I wanted to a dropdown list but I am not able to get the data in one dropdown.

### CODE REVIEW

**Review by astakes90 — APPROVED** [review]
It looks great!! The drop down boxes are working splendidly.

**Comment by Happy22LC** [comment]
I can see the dropdown boxes on my end.

**Review by Happy22LC — APPROVED** [review]

**Review by astakes90 — CHANGES_REQUESTED** [review]
want to wait until we are actually pulling in data before we merge with main

**Comment by priya12845** [comment]
We do not need this branch anymore.

**Pull request closed without merging**
